import { Sen } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

// theme provider ui.shadcn
import { ThemeProvider } from "@/components/Theme/ThemeProvider";

const SenFont = Sen({
  weight: ["400","500","600","700"],
  subsets: ["latin"],
  display: "swap",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${SenFont.variable}   antialiased`}
        suppressHydrationWarning={true} 
      >
        <ThemeProvider attribute="class" defaultTheme="light" >
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
